---
language: python
python:   "2.7"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get remove -qq --purge apache2 apache2-utils

install:
  - pip install ansible

script:
  - ansible-playbook tests/test.yml -i test/inventory --syntax-check 
  - ansible-playbook tests/test.yml -i test/inventory --connection=local --sudo -vvv

