---

- include: install.yml
  tags: apache_install

- include: vhosts.yml
  tags: apache_config

- include: ssl.yml
  tags: apache_ssl

- include: modules.yml
  tags: apache_modules

- name: Enable service
  service: 
    name=apache2 
    enabled=yes

# vi:ts=2:sw=2:et:ft=yaml
